Added CLI library
melvinw/tracer pull request #7
Opened 2022-04-07 06:07 UTC by kishore-ganesh

What I did:

1. Added the CLI11 Library and just wired in the existing options into it

Signed-off-by: Kishore Ganesh <kishore2912000@gmail.com>

2022-04-07 20:36 UTC, melvinw requested changes
Thanks! Just a few small things inline

2022-04-07 20:36 UTC, melvinw commented on src/main.cc
> +#include<CLI/CLI.hpp>
can you move this up with the other third-party includes (between `<bvh/*>` and `<glm/*>`)? also, missed a space:
```suggestion
#include <CLI/CLI.hpp>
```

2022-04-07 20:36 UTC, melvinw commented on src/main.cc
> +int parse_time(std::string& time_string, struct tm& tv, int& tz){
Could you change this to the following? It's a little bit easier for me to understand than these mutable references.
```suggestion
std::optional<std::pair<struct tm, int>> parse_time(const std::string &time_string) {
```

2022-04-07 20:36 UTC, melvinw commented on src/main.cc
> +  std::string gltf_path = "";
`= ""` isn't necessary here. the default constructor for `std::string` will initialize to the empty string

2022-04-07 20:36 UTC, melvinw commented on src/main.cc
> +  std::string time_string = "";
same thing about `=""` here

2022-04-07 20:36 UTC, melvinw commented on src/main.cc
> +      assert(err==0);
if you take my suggestion above about `parse_time()` this could then be
```suggestion
      auto time = parse_time(time_string);
      assert(time.has_value());
      auto [tv, tz] = time.value();
```

2022-04-07 20:36 UTC, melvinw commented on src/main.cc
> +
nit: extraneous whitespace could be dropped

2022-04-07 20:36 UTC, melvinw commented on src/main.cc
> +  tv.tm_hour = 12;
nit: move this down to where `tz` is declared, closer to where it's used

2022-04-07 20:36 UTC, melvinw commented on src/main.cc
> +  CLI::Option* time_option = app.add_option("--time", time_string, "Time of day");
Can you include a note that says the timestamp must match `%Y-%m-%dT%H:%M%:S[-/+%H:%M]`?

2022-04-08 06:37 UTC, kishore-ganesh commented
@melvinw I've changed it to std::optional and have changed the rest as per your suggestions. However, I think we won't be able to use auto [tv, tz]  since tv and tz are already declared, so I've assigned it to temporaries and reassigned them (Is there a better way to do this?).

2022-04-08 15:04 UTC, melvinw commented
Ah right, I forgot structured bindings don't work that way. You should be able to do `std::tie(tv, tz) = ...` I think

2022-04-08 18:08 UTC, kishore-ganesh commented
Yes, that worked!

2022-04-09 00:15 UTC, melvinw approved these changes
Looks good. Thanks!

2022-04-09 00:16 UTC, merged